export const advertStyles = [
  {
    id: 1,
    name: 'test1',
    banner: {
      primary: '#e0c5cf',
      secondary: '#b4d4e2',
      textColor: '#615363',
      border: '1px solid #e7eef1',
    },
    background: {
      border: '',
      borderRadius: '50%',
      background: 'radial-gradient(circle, #82b7a9, #9cc9cc, #c1d9e5, #e4eaf4, #ffffff, #ffffff,#ffffff, #ffffff, #ffffff )',
      shadow: '',
    },
    title: {
      border: '2px solid #e7eef1',
      borderTop: '',
      borderRight: '',
      borderLeft: '',
      borderBottom: '',
      color: '#615363',
      background: '#b4d4e2',
      shadow: '0 0 10px #394950',
    },
    containers: {
      borderRadius: '2rem',
      primary: {
        background: '#b4d4e2',
        border: '2px solid #e7eef1',
        shadow: '0 0 10px #394950',
        textColor: '#615363',
      },
      secondary: {
        borderTop: '',
        borderRight: '',
        borderLeft: '',
        borderBottom: '',
        background: '#e0c5cf',
        border: '2px solid #e7eef1',
        shadow: '0 0 10px #503b41',
        textColor: '#615363',
      },
    },
    font: "'Mukta', sans-serif",
    letterSpacing: '',
  },
  {
    id: 2,
    name: 'test2',
    banner: {
      primary: '#a13028',
      secondary: '#6f73a7',
      textColor: 'white',
      border: '1px solid #a13028',
    },
    background: {
      border: '',
      borderRadius: '',
      background: '',
      shadow: '',
    },
    title: {
      border: '',
      borderTop: '',
      borderRight: '',
      borderLeft: '',
      borderBottom: '',
      color: 'white',
      background: '#a13028',
      shadow: '',
    },
    containers: {
      borderRadius: '',
      primary: {
        borderTop: '',
        borderRight: '7px solid #a13028',
        borderLeft: '7px solid #a13028',
        borderBottom: '',
        background: '#6f73a7',
        border: '',
        shadow: '',
        textColor: 'white',
      },

      secondary: {
        borderTop: '',
        borderRight: '7px solid #a13028',
        borderLeft: '7px solid #a13028',
        borderBottom: '',
        background: '#6f73a7',
        border: '',
        shadow: '',
        textColor: 'white',
      },
    },
    font: "'Mulish', sans-serif",
    letterSpacing: '',
  },
  {
    id: 3,
    name: 'test3',
    banner: {
      primary: '#b6e081',
      secondary: '#dee762',
      textColor: '#41522a',
      border: '1px solid black',
    },
    background: {
      border: '',
      borderRadius: '',
      background: '',
      shadow: 'inset 0 0 10px black',
    },
    title: {
      border: '',
      borderTop: '',
      borderRight: '',
      borderLeft: '',
      borderBottom: '',
      color: '#485053',
      background: '#b6e081',
      shadow: '5px 5px 10px black',
    },
    containers: {
      borderRadius: '',
      primary: {
        borderTop: '',
        borderRight: '',
        borderLeft: '',
        borderBottom: '',
        background: '#b6e081',
        border: '',
        shadow: '5px 5px 10px black',
        textColor: '#41522a',
      },
      secondary: {
        borderTop: '',
        borderRight: '',
        borderLeft: '',
        borderBottom: '',
        background: '#dee762',
        border: '1px solid #b9e420',
        shadow: '5px 5px 10px black',
        textColor: '#41522a',
      },
    },
    font: "'Spline Sans Mono', monospace",
    letterSpacing: '0',
  },
  {
    id: 4,
    name: 'test4',
    banner: {
      primary: '#8782b675',
      secondary: '#8782b6',
      textColor: '#1b173f',
      border: '1px dotted #1b173f',
    },
    background: {
      border: '',
      borderRadius: '1rem',
      background: '#8782b675',
      shadow: '',
    },
    title: {
      border: '',
      borderTop: '1px dotted #1b173f',
      borderRight: '',
      borderLeft: '',
      borderBottom: '1px dotted #1b173f',
      color: '#1b173f',
      background: '#6257c247',
      shadow: '',
    },
    containers: {
      borderRadius: '',
      primary: {
        borderTop: '',
        borderRight: '',
        borderLeft: '',
        borderBottom: '',
        background: '#6257c247',
        border: '1px dotted #1b173f',
        shadow: '',
        textColor: '#1b173f',
      },

      secondary: {
        borderTop: '1px dotted #1b173f',
        borderRight: '',
        borderLeft: '',
        borderBottom: '1px dotted #1b173f',
        background: '#6257c247',
        border: '',
        shadow: '',
        textColor: '#1b173f',
      },
    },
    font: "'Dancing Script', cursive",
    letterSpacing: '',
  },
];
