export const advertStyles = [
  {
    id: 1,
    name: 'pastel',
    banner: {
      primary: '#e0c5cf',
      secondary: '#b4d4e2',
      textColor: '#615363',
      border: '1px solid #e7eef1',
    },
    background: {
      border: '',
      borderRadius: '50%',
      background: 'radial-gradient(circle, #82b7a9, #9cc9cc, #c1d9e5, #e4eaf4, #ffffff, #ffffff,#ffffff, #ffffff, #ffffff )',
      shadow: '',
    },
    title: {
      border: '2px solid #e7eef1',
      borderTop: '',
      borderRight: '',
      borderLeft: '',
      borderBottom: '',
      color: '#615363',
      background: '#b4d4e2',
      shadow: '0 0 10px #394950',
    },
    containers: {
      borderRadius: '2rem',
      primary: {
        background: '#b4d4e2',
        border: '2px solid #e7eef1',
        shadow: '0 0 10px #394950',
        textColor: '#615363',
      },
      secondary: {
        borderTop: '',
        borderRight: '',
        borderLeft: '',
        borderBottom: '',
        background: '#e0c5cf',
        border: '2px solid #e7eef1',
        shadow: '0 0 10px #503b41',
        textColor: '#615363',
      },
    },
    font: "'Oxygen', sans-serif",
  },
  {
    id: 2,
    name: 'currant',
    banner: {
      primary: '#a13028',
      secondary: '#6f73a7',
      textColor: 'white',
      border: '1px solid #a13028',
    },
    background: {
      border: '',
      borderRadius: '50%',
      background: 'radial-gradient(circle, #6f73a7dd, #886099b7, #9e4a7c8f, #a8365671, #a130284b, #ffffff, #ffffff, #ffffff, #ffffff, #ffffff, #ffffff);',
      shadow: '',
    },
    title: {
      border: '',
      borderTop: '',
      borderRight: '',
      borderLeft: '',
      borderBottom: '',
      color: 'white',
      background: '#a13028',
      shadow: '0 0 5px 2px #3b120f',
    },
    containers: {
      borderRadius: '',
      primary: {
        borderTop: '',
        borderRight: '7px solid #a13028',
        borderLeft: '7px solid #a13028',
        borderBottom: '',
        background: '#6f73a7',
        border: '',
        shadow: '0 0 5px 2px #393b55',
        textColor: 'white',
      },

      secondary: {
        borderTop: '',
        borderRight: '7px solid #a13028',
        borderLeft: '7px solid #a13028',
        borderBottom: '',
        background: '#6f73a7',
        border: '',
        shadow: '0 0 5px 2px #2f3146',
        textColor: 'white',
      },
    },
    font: "'Mulish', sans-serif",
  },
  {
    id: 3,
    name: 'retro',
    banner: {
      primary: '#b6e081',
      secondary: '#dee762',
      textColor: '#41522a',
      border: '1px solid black',
    },
    background: {
      border: '',
      borderRadius: '',
      background: '',
      shadow: 'inset 0 0 10px black',
    },
    title: {
      border: '',
      borderTop: '',
      borderRight: '',
      borderLeft: '',
      borderBottom: '',
      color: '#485053',
      background: '#b6e081',
      shadow: '5px 5px 10px black',
    },
    containers: {
      borderRadius: '',
      primary: {
        borderTop: '',
        borderRight: '',
        borderLeft: '',
        borderBottom: '',
        background: '#b6e081',
        border: '',
        shadow: '5px 5px 10px black',
        textColor: '#41522a',
      },
      secondary: {
        borderTop: '',
        borderRight: '',
        borderLeft: '',
        borderBottom: '',
        background: '#dee762',
        border: '1px solid #b9e420',
        shadow: '5px 5px 10px black',
        textColor: '#41522a',
      },
    },
    font: "'Spline Sans Mono', monospace",
  },
  {
    id: 4,
    name: 'elegant',
    banner: {
      primary: '#8782b675',
      secondary: '#8782b6',
      textColor: '#1b173f',
      border: '1px dotted #1b173f',
    },
    background: {
      border: '',
      borderRadius: '1rem',
      background: '#8782b675',
      shadow: '',
    },
    title: {
      border: '',
      borderTop: '1px dotted #1b173f',
      borderRight: '',
      borderLeft: '',
      borderBottom: '1px dotted #1b173f',
      color: '#1b173f',
      background: '#6257c247',
      shadow: '',
    },
    containers: {
      borderRadius: '',
      primary: {
        borderTop: '',
        borderRight: '',
        borderLeft: '',
        borderBottom: '',
        background: '#6257c247',
        border: '1px dotted #1b173f',
        shadow: '',
        textColor: '#1b173f',
      },

      secondary: {
        borderTop: '1px dotted #1b173f',
        borderRight: '',
        borderLeft: '',
        borderBottom: '1px dotted #1b173f',
        background: '#6257c247',
        border: '',
        shadow: '',
        textColor: '#1b173f',
      },
    },
    font: "'Dancing Script', cursive",
  },
  {
    id: 5,
    name: 'playful',
    banner: {
      primary: '#9FEDD7',
      secondary: '#FCE181',
      textColor: '#026670',
      border: '1px dashed #026670',
    },
    background: {
      border: '',
      borderRadius: '2.5rem',
      background: '#EDEAE5',
      shadow: '',
    },
    title: {
      border: '1px dashed #026670',
      borderTop: '',
      borderRight: '',
      borderLeft: '',
      borderBottom: '',
      color: '#026670',
      background: '#9FEDD7',
      shadow: '',
    },
    containers: {
      borderRadius: '2rem',
      primary: {
        borderTop: '',
        borderRight: '',
        borderLeft: '',
        borderBottom: '',
        background: '#9FEDD7',
        border: '1px dashed #026670',
        shadow: '',
        textColor: '#1b173f',
      },

      secondary: {
        borderTop: '',
        borderRight: '',
        borderLeft: '',
        borderBottom: '',
        background: '#FCE181',
        border: '1px dashed #026670',
        shadow: '',
        textColor: '#1b173f',
      },
    },
    font: "'Dancing Script', cursive",
  },
  {
    id: 6,
    name: 'minimal',
    banner: {
      primary: '#dfcab586',
      secondary: '#dfcab5',
      textColor: '#4d4c4b',
      border: '2px dashed #E98074',
    },
    background: {
      border: '',
      borderRadius: '3rem',
      background: '#dfcab549',
      shadow: '0 0 20px -5px #a58668',
    },
    title: {
      border: '',
      borderTop: '',
      borderRight: '',
      borderLeft: '',
      borderBottom: '',
      color: '#4d4c4b',
      background: '',
      shadow: '',
    },
    containers: {
      borderRadius: '2rem',
      primary: {
        borderTop: '',
        borderRight: '2px dashed #E98074',
        borderLeft: '2px dashed #E98074',
        borderBottom: '',
        background: '',
        border: '',
        shadow: '',
        textColor: '#4d4c4b',
      },

      secondary: {
        borderTop: '',
        borderRight: '2px dashed #E98074',
        borderLeft: '2px dashed #E98074',
        borderBottom: '2px dashed #E98074',
        background: '',
        border: '',
        shadow: '',
        textColor: '#4d4c4b',
      },
    },
    font: "'Roboto', sans-serif",
  },
  {
    id: 7,
    name: 'social media',
    banner: {
      primary: '#123c6922',
      secondary: '#3b81cc',
      textColor: '#123C69',
      border: '',
    },
    background: {
      border: '',
      borderRadius: '',
      background: '',
      shadow: '',
    },
    title: {
      border: '',
      borderTop: '',
      borderRight: '5px solid #00000065',
      borderLeft: '5px solid #00000065',
      borderBottom: '',
      color: '#d4dbe2',
      background: '#2869af',
      shadow: '5px 5px 10px #143253',
    },
    containers: {
      borderRadius: '2rem',
      primary: {
        borderTop: '',
        borderRight: '',
        borderLeft: '',
        borderBottom: '',
        background: '#2869af',
        border: '',
        shadow: '5px 5px 5px #143253',
        textColor: '#d4dbe2',
      },
      secondary: {
        borderTop: '',
        borderRight: '5px solid #b7b4c7',
        borderLeft: '5px solid #b7b4c7',
        borderBottom: '',
        background: '#123c6922',
        border: '',
        shadow: '5px 5px 10px #30373f',
        textColor: '#123C69',
      },
    },
    font: "'Pacifico', cursive",
  },
  {
    id: 8,
    name: 'letter',
    banner: {
      primary: '#cfcfcf',
      secondary: '#ffffff',
      textColor: '#000000',
      border: '2px dashed black',
    },
    background: {
      border: '2px dashed black',
      borderRadius: '',
      background: '',
      shadow: '0 0 20px black',
    },
    title: {
      border: '',
      borderTop: '',
      borderRight: '',
      borderLeft: '',
      borderBottom: '2px dashed black',
      color: '',
      background: '',
      shadow: '',
    },
    containers: {
      borderRadius: '',
      primary: {
        borderTop: '',
        borderRight: '',
        borderLeft: '',
        borderBottom: '',
        background: '',
        border: '2px dashed black',
        shadow: '',
        textColor: '',
      },
      secondary: {
        borderTop: '',
        borderRight: '',
        borderLeft: '',
        borderBottom: '2px dashed black',
        background: '',
        border: '',
        shadow: '',
        textColor: '#000000',
      },
    },
    font: "'Dancing Script', cursive",
  },
];
